# Generated by Django 3.2.4 on 2021-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rsimg',
            field=models.ImageField(default='ics.jpg', upload_to='Restaurantimages/'),
        ),
    ]
