# Generated by Django 3.2.4 on 2021-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_restaurant_rsimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=50)),
                ('icategory', models.CharField(choices=[('NV', 'Non-Veg'), ('VG', 'Veg'), ('Df', 'Select Item Type')], default='Df', max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('iimage', models.ImageField(default='ics.jpg', upload_to='Itemimages/')),
                ('itavailability', models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available'), ('Sl', 'Select Availability')], default='Sl', max_length=20)),
            ],
        ),
    ]
